apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jenkinsc-dev
  namespace: build-infra-jenkins-dev
resources:
  - ../../base
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: jenkinsc
    path: jenkins.yaml
  
