#managed files
controller:
  JCasC:
    enabled: true
    configScripts:
      unclassified: |-            
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      id: "jira-credentials"
                      password: "test"
                      scope: GLOBAL
                      username: "jira"
                      usernameSecret: true
        jenkins: 
          
          securityRealm:
            github:
              githubWebUri: "https://github.com"
              githubApiUri: "https://api.github.com"
              clientID: ${gitouth-gitid}
              clientSecret: ${gitouth-gittoken}
              oauthScopes: "read:org,user:email"
          
          systemMessage: Welcome to our CI\CD server update jfrog.
          
          globalNodeProperties: 
          - envVars: 
              env: 
              - key: "BUILD_REPORT_SPACE_ID"
                value: "1234"
              - key: "BUILD_RESOURCES_BRANCH"
                value: "develop"                  
           
        unclassified:  
          jiraCloudPluginConfig: 
            sites:
              - credentialsId: "jira-credentials"
                site: "superna.atlassian.net"
                webhookUrl: "https://somevalue"
