apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-c
  labels:
    volume-type: nfs 
spec:
  capacity:
    storage: 1Gi 
  storageClassName: local-path
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: "/home/satya/nfs_a" 
    server: 172.26.3.244
    readOnly: false
