apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-c
  namespace: build-infra-jenkins
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume-type: nfs
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: nfs-pv-c
  
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  phase: Bound
